#ifndef ZENI_CONCURRENCY_HPP
#define ZENI_CONCURRENCY_HPP

//#include <new>

#ifndef ZENI_CONCURRENCY
#define ZENI_CONCURRENCY ZENI_CONCURRENCY_LOCKFREE
#endif

#ifndef ZENI_CONCURRENCY_DESTRUCTIVE_INTERFERENCE_SIZE
//#define ZENI_CONCURRENCY_DESTRUCTIVE_INTERFERENCE_SIZE std::hardware_destructive_interference_size
#define ZENI_CONCURRENCY_DESTRUCTIVE_INTERFERENCE_SIZE 64
#endif

#ifndef ZENI_CONCURRENCY_CONSTRUCTIVE_INTERFERENCE_SIZE
//#define ZENI_CONCURRENCY_CONSTRUCTIVE_INTERFERENCE_SIZE std::hardware_constructive_interference_size
#define ZENI_CONCURRENCY_CONSTRUCTIVE_INTERFERENCE_SIZE 64
#endif

#define ZENI_CONCURRENCY_CACHE_ALIGN alignas(ZENI_CONCURRENCY_DESTRUCTIVE_INTERFERENCE_SIZE)
#define ZENI_CONCURRENCY_CACHE_ALIGN_TOGETHER alignas(ZENI_CONCURRENCY_CONSTRUCTIVE_INTERFERENCE_SIZE)

#define ZENI_CONCURRENCY_NONE 0
#define ZENI_CONCURRENCY_LOCKING 1
#define ZENI_CONCURRENCY_LOCKFREE 2

#if ZENI_CONCURRENCY != ZENI_CONCURRENCY_NONE && ZENI_CONCURRENCY != ZENI_CONCURRENCY_LOCKING && ZENI_CONCURRENCY != ZENI_CONCURRENCY_LOCKFREE
static_assert(false, "ZENI_CONCURRENCY must be ZENI_CONCURRENCY_NONE, ZENI_CONCURRENCY_LOCKING, or ZENI_CONCURRENCY_LOCKFREE!");
#endif

#endif
